name: GitHub Development Deploy Demo
run-name: ${{ github.actor }} is deploying to Dev 🚀
on:
  push:
    branches-ignore:
      - main
jobs:
  Development:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - run: echo "DEVELOPMENT DEPLOYMENT"
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
